global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'kube-state-metrics'
    static_configs:
      - targets: ['kube-state-metrics.final-project-devsecops.svc.cluster.local:8080']

  - job_name: 'webgoat'
    metrics_path: '/WebGoat/actuator/prometheus'
    static_configs:
      - targets: ['final-project-service.final-project-devsecops.svc.cluster.local:8080']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
