apiVersion: v1
kind: ResourceQuota
metadata:
  name:  webgoat-quota
  namespace: final-project-devsecops
spec:
  hard:
    requests.cpu: "4"
    requests.memory: "2Gi"
    limits.cpu: "8"
    limits.memory: "4Gi"
    pods: "15"
