apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-app
  namespace: final-project-devsecops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: final-project-app
  template:
    metadata:
      labels:
        app: final-project-app
    spec:
      containers:
        - name: final-project-container
          image: oliviertremblaynoel/log8100-projet
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
